version: "3"
services:
    php-fmp:
        container_name: php-fpm
        build: 
            context: .
            dockerfile: docker/php.Dockerfile
        volumes: 
            - ./:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/log
        links: 
            - postgres

    nginx:
        container_name: nginx
        build:
            context: .
            dockerfile: docker/nginx.Dockerfile
        ports: 
            - "8084:80"
        volumes: 
            - ./:/var/www/symfony
            - ./logs/nginx/:/var/log/nginx
        links: 
            - php-fmp
    
    postgres:
        container_name: postgres
        image: postgres
        environment:
            POSTGRES_DB: demo_db
            POSTGRES_USER: demo_usr
            POSTGRES_PASSWORD: demo_pwd
        volumes:
            - ./data/postgresql/demo_db:/var/lib/postgresql/data
        ports:
            - 5432:5432   
